"""empty message

Revision ID: c171c9171d5b
Revises: 
Create Date: 2024-11-19 18:59:56.515300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c171c9171d5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('birth_year', sa.String(length=40), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('skin_color', sa.String(length=40), nullable=True),
    sa.Column('eye_color', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('climate', sa.String(length=40), nullable=True),
    sa.Column('population', sa.String(length=40), nullable=True),
    sa.Column('orbital_period', sa.String(length=50), nullable=True),
    sa.Column('rotation_period', sa.String(length=40), nullable=True),
    sa.Column('diameter', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
